apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation
spec:
  replicas: 10
  selector:
    matchLabels:
      app: simulation
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
        - name: simulation
          image: cguillo/simulation
          imagePullPolicy: Always
